title = "Config"

# specify the logging level (TRACE, DEBUG, INFO, ERROR, CRITICAL)
log_level = "INFO"

[client]
endpoint = "127.0.0.1"
port = 1194 # Default port for OpenVPN server

[server]
endpoint = "0.0.0.0"
port = 53

[packet]
protocol = "dns" # Options: dns, none
encoding = "base85" # Options: base64, base85, none
mode = "server"
# Determines whether to run in server or client mode
# server mode:
#                      [ ------------- Tunnel over Anything --------------]
#   encoded packets -> server connector -> disassembler -> client connector -> raw data
#   encoded packets <- server connector <-   assembler  <- client connector <- raw data
#
# client mode:
#                      [ ------------- Tunnel over Anything --------------]
#          raw data -> server connector ->   assembler  -> client connector -> encoded data
#          raw data <- server connector <- disassembler <- client connector <- encoded data